name: build

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: true

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v2


      - name: Build ReShade (64-bit)
        run: |
          msbuild ReShade.sln /p:Configuration=Release /p:Platform=64-bit


      - name: Upload ReShade (64-bit)
        uses: actions/upload-artifact@v4
        with:
          name: ReShade (64-bit)
          path: './bin/x64/Release/ReShade64.dll'

      - name: Build Examples (64-bit)
        run: |
          msbuild examples/Examples.sln /p:Configuration=Release /p:Platform=64-bit

      - name: Archive Examples (64-bit)
        run: |
          python 'tools/archive_examples.py'
          
    - name: Upload Examples (64-bit)
        uses: actions/upload-artifact@
        with:
          name: Examples 
          path: 'Examples64.zip'
